version: '3.8'

services:
    php:
        build:
            context: ./docker/php
        working_dir: /app
        volumes:
            - ./:/app
    nginx:
        image: nginx:1.23.3-alpine
        working_dir: /app
        volumes:
            - ./:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "127.0.0.1:8080:80"
    db:
        image: mysql:8.0.32
        environment:
            - MYSQL_DATABASE=app
            - MYSQL_USER=app
            - MYSQL_PASSWORD=nopassword
            - MYSQL_RANDOM_ROOT_PASSWORD=1
        ports:
            - "127.0.0.1:4306:3306"
