parameters:
    phone_number_carrier_score_config:
        default_score: 1
        carrier_scores:
            -
                name: Megafon
                score: 10
                codes:
                    - 902
                    - 904
                    - 908
                    - 920
                    - 921
                    - 922
                    - 923
                    - 924
                    - 925
                    - 926
                    - 927
                    - 928
                    - 929
                    - 930
                    - 931
                    - 932
                    - 933
                    - 934
                    - 936
                    - 937
                    - 938
                    - 939
                    - 950
                    - 951
                    - 958
                    - 999
            -
                name: Beeline
                score: 5
                codes:
                    - 900
                    - 902
                    - 903
                    - 904
                    - 905
                    - 906
                    - 908
                    - 909
                    - 930
                    - 933
                    - 950
                    - 951
                    - 953
                    - 960
                    - 961
                    - 962
                    - 963
                    - 964
                    - 965
                    - 966
                    - 967
                    - 968
                    - 969
                    - 980
                    - 983
                    - 986
                    - 994
            -
                name: MTS
                score: 3
                codes:
                    - 901
                    - 902
                    - 904
                    - 908
                    - 910
                    - 911
                    - 912
                    - 913
                    - 914
                    - 915
                    - 916
                    - 917
                    - 918
                    - 919
                    - 950
                    - 958
                    - 978
                    - 980
                    - 981
                    - 982
                    - 983
                    - 984
                    - 985
                    - 986
                    - 987
                    - 988
                    - 989
