clients_list:
    path: /
    controller: App\Controller\ClientController::list

clients_create:
    path: /clients/create
    controller: App\Controller\ClientController::create

clients_edit:
    path: /clients/{id}/edit
    controller: App\Controller\ClientController::edit
    requirements:
        id: '\d+'
